import argparse
import os
import pickle

from configs import CONFIGS, SetFlowConfig
from inference import run_inference

# configs.py keeps the plain baseline out of CONFIGS (it is commented out of
# _configs_list), but run_inference looks its config up by name.
CONFIGS.setdefault("baseline", SetFlowConfig(name="baseline"))

# The reviewer asked for 5/10/20/50/100%. 20% is already reported in
# Table~\ref{tab:classification}, so it is not regenerated by default.
DEFAULT_RATIOS = [0.05, 0.1, 0.5, 1.0]

ENCODERS = {
    "msl": dict(
        weights_dir="weights/abl-msl-128",
        input_pkl="/lustre/nj/cvpr2026/pickles/pca/msl-128.pkl",
        out_dir="/lustre/nj/cvpr2026/pickles/setflow/ratios-msl-128",
    ),
    "v2": dict(
        weights_dir="weights/abl-v2-128",
        input_pkl="/lustre/nj/cvpr2026/pickles/pca/v2-128.pkl",
        out_dir="/lustre/nj/cvpr2026/pickles/setflow/ratios-v2-128",
    ),
}


def ratio_name(ratio):
    return f"ratio_{round(ratio * 100):02d}"


def write_zero_ratio(input_pkl, out_dir, config_name):
    """Pack the real training split as the 0% pickle -- no model, no sampling.

    Deliberately rebuilt the way run_inference() packs its output rather than
    copied: run_inference reads only train_ds[0] and reshapes y/w to (b, 1), so
    a plain file copy would differ in structure whenever train_ds holds more
    than one element. Going through the same shaping keeps ratio_00 different
    from the other ratios in exactly one respect -- it has no bonus bags.
    """
    save_dir = os.path.join(out_dir, config_name)
    os.makedirs(save_dir, exist_ok=True)
    output_pkl = os.path.join(save_dir, "combined.pkl")

    train_ds, valid_ds, test_ds = pickle.load(open(input_pkl, "rb"))
    x, y, w, group, instance_type = train_ds[0]
    # run_inference does y.view(-1) and then rearrange('b -> b 1')
    train_ds_0 = [(x, y.view(-1, 1), w.view(-1, 1), group, instance_type)]

    pickle.dump(
        (train_ds_0, valid_ds, test_ds),
        open(output_pkl, "wb"),
        protocol=pickle.HIGHEST_PROTOCOL,
    )
    return output_pkl


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--ratios", nargs="*", type=float, default=DEFAULT_RATIOS)
    parser.add_argument("--encoders", nargs="*", default=sorted(ENCODERS), choices=sorted(ENCODERS))
    parser.add_argument("--config", default="baseline")
    parser.add_argument("--weights_dir_msl", default=ENCODERS["msl"]["weights_dir"])
    parser.add_argument("--weights_dir_v2", default=ENCODERS["v2"]["weights_dir"])
    parser.add_argument("--pkl_msl", default=ENCODERS["msl"]["input_pkl"])
    parser.add_argument("--pkl_v2", default=ENCODERS["v2"]["input_pkl"])
    parser.add_argument("--out_dir_msl", default=ENCODERS["msl"]["out_dir"])
    parser.add_argument("--out_dir_v2", default=ENCODERS["v2"]["out_dir"])
    return parser.parse_args()


def main():
    args = parse_args()

    if args.config not in CONFIGS:
        raise ValueError(f"Unknown config: {args.config}")

    paths = {
        "msl": dict(weights_dir=args.weights_dir_msl, input_pkl=args.pkl_msl, out_dir=args.out_dir_msl),
        "v2": dict(weights_dir=args.weights_dir_v2, input_pkl=args.pkl_v2, out_dir=args.out_dir_v2),
    }

    for encoder in args.encoders:
        p = paths[encoder]
        weights_path = os.path.join(p["weights_dir"], args.config, "setflow.pth")

        for ratio in args.ratios:
            name = ratio_name(ratio)
            out_dir = os.path.join(p["out_dir"], name)

            if ratio == 0:
                # nothing is generated at 0%, so this needs no weights -- which
                # is why the weights check below is per-ratio, not per-encoder
                written = write_zero_ratio(p["input_pkl"], out_dir, args.config)
                print(f"=== {encoder}: packed the real training split as {name} -> {written} ===")
                continue

            if not os.path.exists(weights_path):
                print(f"=== skipping {encoder}/{name}: no weights found at {weights_path} ===")
                continue

            print(f"=== {encoder}: generating {ratio:.0%} bonus bags ({name}) ===")
            run_inference(
                config_name=args.config,
                weights_dir=p["weights_dir"],
                input_pkl=p["input_pkl"],
                out_dir=out_dir,
                bonus_ratio=ratio,
                # only the combined set varies with the ratio; the
                # synthetic-only set would be identical every time
                write_synthetic=False,
            )


if __name__ == "__main__":
    main()
