import argparse
import os

from configs import CONFIGS, SetFlowConfig
from inference import run_inference

# configs.py keeps the plain baseline out of CONFIGS (it is commented out of
# _configs_list), but run_inference looks its config up by name.
CONFIGS.setdefault("baseline", SetFlowConfig(name="baseline"))

# The reviewer asked for 5/10/20/50/100%. 20% is already reported in
# Table~\ref{tab:classification}, so it is not regenerated by default.
DEFAULT_RATIOS = [0.05, 0.1, 0.5, 1.0]

ENCODERS = {
    "msl": dict(
        weights_dir="weights/abl-msl-128",
        input_pkl="/lustre/nj/cvpr2026/pickles/pca/msl-128.pkl",
        out_dir="/lustre/nj/cvpr2026/pickles/setflow/ratios-msl-128",
    ),
    "v2": dict(
        weights_dir="weights/abl-v2-128",
        input_pkl="/lustre/nj/cvpr2026/pickles/pca/v2-128.pkl",
        out_dir="/lustre/nj/cvpr2026/pickles/setflow/ratios-v2-128",
    ),
}


def ratio_name(ratio):
    return f"ratio_{round(ratio * 100):02d}"


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--ratios", nargs="*", type=float, default=DEFAULT_RATIOS)
    parser.add_argument("--encoders", nargs="*", default=sorted(ENCODERS), choices=sorted(ENCODERS))
    parser.add_argument("--config", default="baseline")
    parser.add_argument("--weights_dir_msl", default=ENCODERS["msl"]["weights_dir"])
    parser.add_argument("--weights_dir_v2", default=ENCODERS["v2"]["weights_dir"])
    parser.add_argument("--pkl_msl", default=ENCODERS["msl"]["input_pkl"])
    parser.add_argument("--pkl_v2", default=ENCODERS["v2"]["input_pkl"])
    parser.add_argument("--out_dir_msl", default=ENCODERS["msl"]["out_dir"])
    parser.add_argument("--out_dir_v2", default=ENCODERS["v2"]["out_dir"])
    return parser.parse_args()


def main():
    args = parse_args()

    if args.config not in CONFIGS:
        raise ValueError(f"Unknown config: {args.config}")

    paths = {
        "msl": dict(weights_dir=args.weights_dir_msl, input_pkl=args.pkl_msl, out_dir=args.out_dir_msl),
        "v2": dict(weights_dir=args.weights_dir_v2, input_pkl=args.pkl_v2, out_dir=args.out_dir_v2),
    }

    for encoder in args.encoders:
        p = paths[encoder]
        weights_path = os.path.join(p["weights_dir"], args.config, "setflow.pth")
        if not os.path.exists(weights_path):
            print(f"=== skipping {encoder}: no weights found at {weights_path} ===")
            continue

        for ratio in args.ratios:
            name = ratio_name(ratio)
            print(f"=== {encoder}: generating {ratio:.0%} bonus bags ({name}) ===")
            run_inference(
                config_name=args.config,
                weights_dir=p["weights_dir"],
                input_pkl=p["input_pkl"],
                out_dir=os.path.join(p["out_dir"], name),
                bonus_ratio=ratio,
                # only the combined set varies with the ratio; the
                # synthetic-only set would be identical every time
                write_synthetic=False,
            )


if __name__ == "__main__":
    main()
