logs_path: /home/nikola.jovisic.ivi/nj/mammo_filter/head_training/logs

input_dim: 384
model_type: velo 
hidden_dim: 8 #always in grid search

full_state: true 
pooler: true #

#velo
#no specifics

#dinout
double_input_layer: #

#baseline
use_tiles: false
aggregation: max

#perceiver
use_shared_projector: true
fusion_mode: linear
layer_norm: false
prehidden_dim: 32

#probably not going to edit much
pos_weight: 1.0
freeze_whole_image_branch: false
flatten: false

#training
batch_size: 4096 #2e16  
lr: 0.02
weight_decay: 1e-4
epochs: 500
patience: 20

#saving
eval_every: 1 
load_path:
save_path: 
